site:
  title: TextFoundry Documentation
  start_page: textfoundry::index.adoc

runtime:
  cache_dir: ./.cache/antora

content:
  sources:
    - url: .
      branches: HEAD
      start_path: doc

output:
  dir: ./public

antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true
      index_by_heading: true

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

asciidoc:
  extensions:
    - asciidoctor-kroki

  attributes:
    kroki-fetch-diagram: false
    page-pagination: ''
    sectanchors: ''
    toc: left
    toclevels: 3
